server:
  port: 8081
  ssl:
    enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr:
    discovery:
      enabled: true
  application:
    name: service-verificationCode
#logging:
#  level:
#    org:
#      springframework:
#        cloud: debug
#    com:
#      alibaba:
#        nacos: debug